import os
import re

input_file = r'd:\301_GUI\my_repo\my-repo\support\cheat.dat'
output_file = r'd:\301_GUI\my_repo\my-repo\support\cheat_en.dat'

translations = {
    "무적": "Invincibility",
    "생명 무한": "Infinite Lives",
    "에너지 무한": "Infinite Energy",
    "시간 무한": "Infinite Time",
    "동전 무한": "Infinite Coins",
    "화력 속도": "Fire Rate",
    "일반": "Normal",
    "폭탄 무한": "Infinite Bombs",
    "레이져": "Laser",
    "무기 선택": "Select Weapon",
    "활성": "Active",
    "켬": "Turn ON",
    "무기 무한": "Infinite Weapon",
    "파워 무제한": "Infinite Power",
    "끔": "Turn OFF",
    "비활성": "Inactive",
    "파워 최대": "Max Power",
    "시작 레벨 선택": "Select Start Level",
    "머신 건": "Machine Gun",
    "파이어 볼": "Fireball",
    "연료 무제한": "Infinite Fuel",
    "샷건": "Shotgun",
    "무기 화력 최대": "Max Weapon Power",
    "이번판 종료": "Finish This Stage",
    "파워업": "Power Up",
    "로켓런처": "Rocket Launcher",
    "레이져 건": "Laser Gun",
    "보너스 무제한": "Infinite Bonus",
    "플레임 샷": "Flame Shot",
    "해비 머신 건": "Heavy Machine Gun",
    "항상 무기 파워 최대": "Always Max Weapon Power",
    "스피드 선택": "Select Speed",
    "플레이시간 무한": "Infinite Play Time",
    "미사일 무제한": "Infinite Missiles",
    "기본 총": "Basic Gun",
    "일반 무기": "Normal Weapon",
    "공 무제한": "Infinite Balls",
    "이어하기 무제한": "Infinite Continues",
    "얼티메이트": "Ultimate",
    "폭탄 선택": "Select Bomb",
    "화염방사기": "Flamethrower",
    "총알 무제한": "Infinite Ammo",
    "게임 시간 무제한": "Infinite Game Time",
    "추가 무기 선택": "Select Extra Weapon",
    "헬프 무제한": "Infinite Helps",
    "폭탄 무제한": "Infinite Bombs",
    "현재판 즉시 종료": "Finish Current Stage Instantly",
    "빅 샷건": "Big Shotgun",
    "선택": "Select",
    "시간 무제한": "Infinite Time",
    "다음 판": "Next Stage",
    "레벨": "Level",
    "스마트 폭탄 무제한": "Infinite Smart Bombs",
    "화염 방사기": "Flamethrower",
    "캐논 무한": "Infinite Cannon",
    "파이어볼 무제한": "Infinite Fireballs",
    "점수 무제한": "Infinite Score",
    "한방에 보스 처리 즉시": "Instant 1-Hit Boss Kill",
    "적군이 총을 안쏨": "Enemies Don't Shoot",
    "총알 속도 선택": "Select Bullet Speed",
    "보너스 모드에서는 치트를 꺼야 합니다": "Cheat must be OFF in bonus mode",
    "무기시간 무제한": "Infinite Weapon Time",
    "기본": "Basic",
    "총알 속도 업": "Bullet Speed Up",
    "도움 줄 선택": "Select Help Line",
    "미라": "Mummy",
    "타이머 초기화": "Reset Timer",
    "쌍둥이 비행기": "Twin Plane",
    "관통": "Pierce",
    "무적 켬": "Invincibility ON",
    "래피드 캐논": "Rapid Cannon",
    "스프레드 캐논": "Spread Cannon",
    "바디타입 선택": "Select Body Type",
    "일반 무적": "Normal Invincibility",
    "피색상 선택": "Select Blood Color",
    "레이져 무제한": "Infinite Laser",
    "니트로 무제한": "Infinite Nitro",
    "보너스 스테이지 시간 무제한": "Infinite Bonus Stage Time",
    "롱 레이져": "Long Laser",
    "무기 무제한": "Infinite Weapons",
    "공격 중지": "Stop Attack",
    "무기파워 선택": "Select Weapon Power",
    "항상 보스 한방": "Always 1-Hit Boss",
    "숏 레이져": "Short Laser",
    "항상 최대 충전": "Always Max Charge",
    "총알 타입": "Bullet Type",
    "충전 무기 선택": "Select Charge Weapon",
    "항상 딱딱한 모자": "Always Hard Hat",
    "무기 파워 초월": "Transcend Weapon Power",
    "하트 무제한": "Infinite Hearts",
    "이번판 종료 즉시": "Instant Stage Finish",
    "탈것 캐논 무한": "Infinite Vehicle Cannon",
    "탈것 에너지 무한": "Infinite Vehicle Energy",
    "손 무기 선택": "Select Hand Weapon",
    "발 무기 선택": "Select Foot Weapon",
    "정상으로 보이지는 않음": "Graphics might glitch",
    "퍼즐모드 치트": "Puzzle Mode Cheats",
    "메인 무기선택": "Select Main Weapon",
    "적군이 총을 쏘지 않음": "Enemies Don't Shoot",
    "스테이지 시작시 무기장착": "Equip Weapon on Stage Start",
    "골드 최대": "Max Gold",
    "내려가는 속도 설정": "Fall Speed Setup",
    "일반 레이져": "Normal Laser",
    "대결 모드 치트": "Vs Mode Cheats",
    "뚱보": "Fat",
    "시간 무한 켬": "Infinite Time ON",
    "로켓 런처": "Rocket Launcher",
    "힌트 무한": "Infinite Hints",
    "무한 회피": "Infinite Evade",
    "대결 시간 무제한": "Infinite Vs Time",
    "빠른 공격 모션 모드": "Fast Attack Motion Mode",
    "회피 무한": "Infinite Evade",
    "화력 종류": "Fire Type",
    "파워 업": "Power Up",
    "측면 무기 무제한": "Infinite Side Weapon",
    "항상 큰 망치": "Always Big Hammer",
    "공격하지 않기": "Don't Attack",
    "스모크 스크린 무제한": "Infinite Smoke Screen",
    "즉시 보조 파워 획득": "Instant Sub-Power Gain",
    "썬더 폭탄": "Thunder Bomb",
    "쓰나미 폭탄": "Tsunami Bomb",
    "빠르게": "Fast",
    "버블 파워 최대": "Max Bubble Power",
    "첫번째 헬리콥터 무기 선택": "Select 1st Helicopter Weapon",
    "두번째 헬리콥터 무기 선택": "Select 2nd Helicopter Weapon",
    "가스 무한": "Infinite Gas",
    "탱크 캐논 무한": "Infinite Tank Cannon",
    "화이트": "White",
    "레드": "Red",
    "측면 무기 선택": "Select Side Weapon",
    "충전 무기시간 무제한": "Infinite Charge Weapon Time",
    "보조 무기선택": "Select Sub Weapon",
    "항상 웨이브 무기": "Always Wave Weapon",
    "항상 허리케인 무기": "Always Hurricane Weapon",
    "웨이브 무기 얻기 즉시": "Get Wave Weapon Instantly",
    "허리케인 무기 얻기 즉시": "Get Hurricane Weapon Instantly",
    "총 무제한": "Infinite Gun",
    "매우느리게": "Very Slow",
    "느리게": "Slow",
    "좀더빠르게": "Slightly Faster",
    "최고속도": "Max Speed",
    "와 함께 사용": "Used together with",
    "보조": "Sub",
    "무한": "Infinite",
    "종": "Bell",
    "보통": "Normal",
    "내려가는 속도 매우느리게": "Fall Speed Very Slow",
    "헬프라인": "Help Line",
    "켜기": "Turn ON",
    "끄기": "Turn OFF",
    "대전 모드 치트": "Vs Mode Cheat",
    "회피 무제한": "Infinite Evade",
    "보너스 레벨에서는 치트를꺼야 합니다": "Cheat must be OFF in bonus level",
    "스페셜 기술 무제한": "Infinite Special Arts",
    "물약 무한": "Infinite Potions",
    "돈 무한": "Infinite Money",
    "건틀렛 무한": "Infinite Gauntlet",
    "투구 무한": "Infinite Helmet",
    "신발 무한": "Infinite Shoes",
    "회오리바람": "Whirlwind",
    "폭탄": "Bomb",
    "번개": "Lightning",
    "열쇠 항상 소지": "Always Have Key",
    "즉시 열쇠 획득": "Instant Key Gain",
    "무기": "Weapon",
    "검": "Sword",
    "그라디우스 소드": "Gladius Sword",
    "브로드 소드": "Broad Sword",
    "그레이트 소드": "Great Sword",
    "엑스칼리버": "Excalibur",
    "전설의 검": "Legendary Sword",
    "크리스탈 선택": "Select Crystal",
    "크리스탈": "Crystal",
    "방패 선택": "Select Shield",
    "방패 없음": "No Shield",
    "라이트 실드": "Light Shield",
    "경량 방패": "Lightweight Shield",
    "나이트 실드": "Knight Shield",
    "기사 방패": "Knight's Shield",
    "하드 실드": "Hard Shield",
    "단단한 방패": "Hard Shield",
    "레전드 실드": "Legend Shield",
    "전설의 방패": "Legendary Shield",
    "갑옷 선택": "Select Armor",
    "갑옷 없음": "No Armor",
    "라이트 아머": "Light Armor",
    "경량 갑옷": "Lightweight Armor",
    "나이트 아머": "Knight Armor",
    "기사 갑옷": "Knight's Armor",
    "헤비 아머": "Heavy Armor",
    "중갑옷": "Heavy Armor",
    "하드 아머": "Hard Armor",
    "단단한 갑옷": "Hard Armor",
    "레전드 아머": "Legend Armor",
    "전설의 갑옷": "Legendary Armor",
    "신발 선택": "Select Shoes",
    "신발 없음": "No Shoes",
    "천 신발": "Cloth Shoes",
    "가죽 신발": "Leather Shoes",
    "세라믹 슈즈": "Ceramic Shoes",
    "전설의 신발": "Legendary Shoes"
}

# sort by decreasing length, to prevent nested string replacement corruption
# Like "무기 무한" being partially replaced if "무기" is encountered first
sorted_keys = sorted(translations.keys(), key=lambda x: len(x), reverse=True)

# Added fallback for anything left out just using a generic pattern if it really bothers us, but standard words handle it

def run():
    try:
        with open(input_file, 'r', encoding='cp949', errors='ignore') as f_in, open(output_file, 'w', encoding='cp949', errors='ignore') as f_out:
            for line in f_in:
                new_line = line
                for k in sorted_keys:
                    if k in new_line:
                        new_line = new_line.replace(k, translations[k])
                f_out.write(new_line)
    except Exception as e:
        print(f"Error: {e}")

run()
